#!/system/bin/sh
#
# discover-amber-node.sh — find the DC-1's amber frontlight LED sysfs node.
# Run AS ROOT on the device (e.g. `adb shell su -c 'sh /data/local/tmp/discover-amber-node.sh'`).
#
# Why this exists: on stock, Daylight's privileged systemrunner app drives a
# second LED channel from the `screen_brightness_amber_rate` setting. On a GSI
# that glue is gone, but the LED + kernel driver remain. This script walks the
# kernel LED/backlight nodes, lets you light each one, and you tell it which one
# is the amber channel. It then writes the config the daemon/CLI use.
#
# SELinux note: if writes are blocked, run `setenforce 0` first (temporary),
# discover the node, then you can re-enable with `setenforce 1`. The Magisk
# module ships an sepolicy allowance so the daemon works with enforcing SELinux.

CONF_DIR=/data/adb/amberd
CONF="$CONF_DIR/config"
mkdir -p "$CONF_DIR"

echo "=== Scanning LED / backlight nodes ==="
CANDIDATES=""
for base in /sys/class/leds /sys/class/backlight; do
  [ -d "$base" ] || continue
  for n in "$base"/*; do
    [ -e "$n/brightness" ] || continue
    max=$(cat "$n/max_brightness" 2>/dev/null || echo "?")
    cur=$(cat "$n/brightness" 2>/dev/null || echo "?")
    printf '  %-50s cur=%-6s max=%s\n' "$n" "$cur" "$max"
    CANDIDATES="$CANDIDATES $n"
  done
done

if [ -z "$CANDIDATES" ]; then
  echo "No writable LED nodes visible. SELinux may be blocking; try: setenforce 0"
  exit 1
fi

echo
echo "Heuristic guesses (name hints for a 2nd/amber/warm channel):"
for n in $CANDIDATES; do
  case "$n" in
    *amber*|*warm*|*-2/*|*_2/*|*2/brightness*|*wled2*|*bl2*|*lcd-backlight1*) echo "  -> $n" ;;
  esac
done

echo
echo "=== Interactive identification ==="
echo "I'll flash each node to its max, then off. Watch the AMBER frontlight."
echo "Set normal screen brightness to a low value first so amber is obvious."
echo

for n in $CANDIDATES; do
  max=$(cat "$n/max_brightness" 2>/dev/null || echo 255)
  orig=$(cat "$n/brightness" 2>/dev/null || echo 0)
  printf "Testing %s (max=%s) ... " "$n" "$max"
  if ! echo "$max" > "$n/brightness" 2>/dev/null; then
    echo "not writable, skipping"
    continue
  fi
  printf "FULL. Is the AMBER light now on? [y/N/q] "
  read ans
  echo "$orig" > "$n/brightness" 2>/dev/null
  case "$ans" in
    y|Y)
      cat > "$CONF" <<EOF
# DC-1 amber frontlight bridge config (generated by discover-amber-node.sh)
AMBER_NODE=$n/brightness
AMBER_NODE_MAX=$max
SETTING_MAX=1023
EOF
      echo
      echo "Saved: $CONF"
      cat "$CONF"
      echo
      echo "Test it:  amberctl set 600   /   amberctl off"
      exit 0 ;;
    q|Q) echo "aborted"; exit 1 ;;
  esac
done

echo "No node identified. If nothing lit up, the amber channel may be gated by"
echo "the panel/composer. Capture 'dmesg | grep -i led' and the full node list"
echo "for a closer look."
exit 1
